name: Parallel Jobs Example

on: push

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Job 1 Step 1
        run: echo "Job 1 Step 1"
      - name: Job 1 Step 2
        run: echo "Job 1 Step 2"

  job2:
    runs-on: self-hosted
    needs: job1
    steps:
      - name: Job 2 Step 1
        run: echo "Job 2 Step 1"
      - name: Job 2 Step 2
        run: echo "Job 2 Step 2"

  job3:
    runs-on: self-hosted
    needs: job1
    steps:
      - name: Job 3 Step 1
        run: echo "Job 3 Step 1"
      - name: Job 3 Step 2
        run: echo "Job 3 Step 2"
