name: PR Opened

on:
  schedule:
    - cron: '* * * * *'

jobs:
  pr-opened:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print pull request number
        run: echo "Hello World"