name: Read Secret

on:
  push:
    branches:
      - master

jobs:
  read-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read secret
        run: echo ${{ secrets.MY_SECRET }}