name: self-hosted

on:
  push:
    branches:
      - master

jobs:
  pr-opened:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print pull request number
        run: echo "PR number"